"""
Fall Detection Module — Phase 2: Trained LSTM (MediaPipe Pose)

How it works:
- MediaPipe PoseLandmarker extracts 33 landmarks per frame (x,y) → 66 features
- Maintains a rolling window of the last N frames (default 30)
- StandardScaler normalizes features (saved from training)
- LSTM outputs probability of fall

Artifacts (generated by training script):
- models/fall_lstm.keras
- models/fall_lstm_scaler.pkl

Note:
- This module is separate from the Phase 1 rules-based detector so you can
  choose either implementation.
"""

from __future__ import annotations

import logging
from collections import deque
from pathlib import Path
from typing import Optional

import numpy as np

from models.fall_detection import FallResult, DEFAULT_MODEL_PATH

logger = logging.getLogger(__name__)

LSTM_MODEL_PATH = Path(__file__).parent / "fall_lstm.keras"
LSTM_SCALER_PATH = Path(__file__).parent / "fall_lstm_scaler.pkl"

LSTM_SEQUENCE_LEN = 30
LSTM_NUM_FEATURES = 66  # 33 keypoints × 2 (x, y)


class LSTMFallDetector:
    """
    Phase 2 fall detector — uses the trained LSTM model instead of fixed rules.

    Maintains a rolling buffer of the last LSTM_SEQUENCE_LEN frames.
    Once the buffer is full it runs inference on every new frame.
    """

    def __init__(
        self,
        model_path: str | None = None,
        scaler_path: str | None = None,
        pose_model_path: str | None = None,
        threshold: float = 0.55,
        sequence_len: int = LSTM_SEQUENCE_LEN,
        cooldown_frames: int = 30,
    ):
        self.model_path = str(model_path or LSTM_MODEL_PATH)
        self.scaler_path = str(scaler_path or LSTM_SCALER_PATH)
        self.pose_model_path = str(pose_model_path or DEFAULT_MODEL_PATH)

        if not Path(self.model_path).exists():
            raise FileNotFoundError(
                f"LSTM model not found at '{self.model_path}'.\n"
                "Train it with: python3.11 scripts/train_lstm.py"
            )
        if not Path(self.scaler_path).exists():
            raise FileNotFoundError(
                f"Scaler not found at '{self.scaler_path}'.\n"
                "Train it with: python3.11 scripts/train_lstm.py"
            )
        if not Path(self.pose_model_path).exists():
            raise FileNotFoundError(
                f"MediaPipe pose model not found at '{self.pose_model_path}'.\n"
                "Download it once with:\n"
                "  curl -L -o models/pose_landmarker.task \\\n"
                "    https://storage.googleapis.com/mediapipe-models/"
                "pose_landmarker/pose_landmarker_full/float16/1/pose_landmarker_full.task"
            )

        import json
        import pickle
        import tempfile
        import zipfile
        import tensorflow as tf
        import mediapipe as mp

        # Workaround: Model saved with Keras 3.13+ includes quantization_config in Dense;
        # Keras 3.10 rejects it. Patch config.json in the .keras zip to remove it.
        model_path = Path(self.model_path)
        with zipfile.ZipFile(model_path, "r") as zf:
            config_bytes = zf.read("config.json")
        config = json.loads(config_bytes)

        def strip_quantization(obj):
            if isinstance(obj, dict):
                obj.pop("quantization_config", None)
                for v in obj.values():
                    strip_quantization(v)
            elif isinstance(obj, list):
                for v in obj:
                    strip_quantization(v)

        strip_quantization(config)
        with tempfile.NamedTemporaryFile(suffix=".keras", delete=False) as tmp:
            with zipfile.ZipFile(model_path, "r") as zf_in:
                with zipfile.ZipFile(tmp.name, "w", zipfile.ZIP_DEFLATED) as zf_out:
                    for name in zf_in.namelist():
                        data = json.dumps(config).encode() if name == "config.json" else zf_in.read(name)
                        zf_out.writestr(name, data)
            self._model = tf.keras.models.load_model(tmp.name)
            Path(tmp.name).unlink(missing_ok=True)
        with open(self.scaler_path, "rb") as f:
            self._scaler = pickle.load(f)

        self.threshold = float(threshold)
        self.sequence_len = int(sequence_len)
        self._buffer: deque[list[float]] = deque(maxlen=self.sequence_len)

        self._cooldown = 0
        self._cooldown_duration = int(cooldown_frames)

        # MediaPipe PoseLandmarker (Tasks API)
        BaseOptions = mp.tasks.BaseOptions
        PoseLandmarker = mp.tasks.vision.PoseLandmarker
        PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
        RunningMode = mp.tasks.vision.RunningMode

        options = PoseLandmarkerOptions(
            base_options=BaseOptions(model_asset_path=self.pose_model_path),
            running_mode=RunningMode.IMAGE,
            num_poses=1,
            min_pose_detection_confidence=0.5,
            min_pose_presence_confidence=0.5,
            min_tracking_confidence=0.5,
        )
        self._mp = mp
        self._landmarker = PoseLandmarker.create_from_options(options)
        logger.info("LSTMFallDetector loaded model from %s", self.model_path)

    def process_frame(self, frame: np.ndarray) -> Optional[FallResult]:
        """Run LSTM fall detection on one BGR frame."""
        import cv2

        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        mp_img = self._mp.Image(
            image_format=self._mp.ImageFormat.SRGB,
            data=np.ascontiguousarray(rgb),
        )
        detection = self._landmarker.detect(mp_img)

        if detection.pose_landmarks and len(detection.pose_landmarks) > 0:
            keypoints: list[float] = []
            for lm in detection.pose_landmarks[0]:
                keypoints.append(float(lm.x))
                keypoints.append(float(lm.y))
        else:
            keypoints = [0.0] * LSTM_NUM_FEATURES

        self._buffer.append(keypoints)

        # Body visibility check — avoid false falls when only face/partial body visible
        non_zero = sum(1 for v in keypoints if v != 0.0)
        if non_zero < LSTM_NUM_FEATURES * 0.5:
            return FallResult(
                is_fall=False,
                confidence=0.0,
                reason="Body not fully visible — move back from camera",
                hip_height=0.0,
                torso_angle_deg=0.0,
                hip_velocity=0.0,
                landmarks_visible=False,
            )

        if len(self._buffer) < self.sequence_len:
            return FallResult(
                is_fall=False,
                confidence=0.0,
                reason=f"Warming up ({len(self._buffer)}/{self.sequence_len} frames)",
                hip_height=0.0,
                torso_angle_deg=0.0,
                hip_velocity=0.0,
                landmarks_visible=bool(detection.pose_landmarks),
            )

        seq = np.array(list(self._buffer), dtype=np.float32)
        seq_flat = seq.reshape(-1, LSTM_NUM_FEATURES)
        seq_flat = self._scaler.transform(seq_flat)
        seq = seq_flat.reshape(1, self.sequence_len, LSTM_NUM_FEATURES)

        prob = float(self._model.predict(seq, verbose=0)[0][0])

        if self._cooldown > 0:
            self._cooldown -= 1
            is_fall = False
        else:
            is_fall = prob >= self.threshold
            if is_fall:
                self._cooldown = self._cooldown_duration

        reason = f"LSTM probability: {prob:.2f}" if is_fall else "standing normally"

        return FallResult(
            is_fall=is_fall,
            confidence=round(prob, 3),
            reason=reason,
            hip_height=0.0,
            torso_angle_deg=0.0,
            hip_velocity=0.0,
            landmarks_visible=bool(detection.pose_landmarks),
        )

    def draw_overlay(self, frame: np.ndarray, result: FallResult) -> np.ndarray:
        """Draw LSTM fall status banner on the frame."""
        import cv2

        h, w = frame.shape[:2]

        if result.is_fall:
            cv2.rectangle(frame, (0, 0), (w, 60), (0, 0, 200), -1)
            cv2.putText(
                frame,
                "  FALL DETECTED (LSTM)",
                (10, 42),
                cv2.FONT_HERSHEY_DUPLEX,
                1.2,
                (255, 255, 255),
                2,
            )
        else:
            cv2.rectangle(frame, (0, 0), (w, 60), (0, 150, 0), -1)
            cv2.putText(
                frame,
                "  Monitoring (LSTM)...",
                (10, 42),
                cv2.FONT_HERSHEY_DUPLEX,
                1.0,
                (255, 255, 255),
                2,
            )

        info = f"LSTM conf={result.confidence:.2f}  {result.reason}"
        cv2.rectangle(frame, (0, h - 35), (w, h), (30, 30, 30), -1)
        cv2.putText(
            frame,
            info,
            (8, h - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.55,
            (200, 200, 200),
            1,
        )
        return frame

    def close(self) -> None:
        self._landmarker.close()
        logger.info("LSTMFallDetector closed")

